freebsd_instance:
  cpu: 1
  memory: 1G

task:
  matrix:
    - name: releases/amd64/13.5-RELEASE
      freebsd_instance:
        image_family: freebsd-13-5
    - name: releases/amd64/14.3-RELEASE
      freebsd_instance:
        image_family: freebsd-14-3
    - name: releases/amd64/15.0-ALPHA1
      freebsd_instance:
        image_family: freebsd-15-0
  stateful: false

  setup_script: pkg install -y ocaml-dune
  build_script: dune build
  test_script: dune test
